# Jim's take on Python math basics with builtins, `math` and `numpy`

## Python math built-ins: `min()`, `max()`, `pow()`, `...`

In [4]:

# Python has some built-in math functions
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

5
25


In [5]:
x = abs(-7.25)

print(x)

7.25


In [6]:
x = pow(4, 3)

print(x)

64


In [7]:
import math

x = math.sqrt(64)

print(x)

8.0


## Python `math` package

In [8]:
import math

x = math.ceil(1.4)
y = math.floor(1.4)

print(x)  # returns 2
print(y)  # returns 1

2
1


## `numpy` the magnificent

In [9]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])  # Create a rank 2 array
print(f"shape: {b.shape}\n"
      f"values:\n{b}")

shape: (2, 3)
values:
[[1 2 3]
 [4 5 6]]


In [10]:
c = np.array([[[1, 2, 3], [4, 5, 6], [4, 5, 6]], [[7, 8, 9], [4, 5, 6], [10, 11, 12]]])

print(f"shape: {c.shape}\n"
      f"values:\n{c}")
print(f"ndim: {c.ndim}")
print(f"size: {c.size}")
print(f"dtype: {c.dtype}")
print(f"itemsize: {c.itemsize} bytes")
print(f"nbytes: {c.nbytes}")
print(f"data: {c.data}")
print(f"value at index [0,0,0]: {c[1,0,0]}")


shape: (2, 3, 3)
values:
[[[ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 4  5  6]
  [10 11 12]]]
ndim: 3
size: 18
dtype: int64
itemsize: 8 bytes
nbytes: 144
data: <memory at 0x107287970>
value at index [0,0,0]: 7


## Re-entering the matrix: hand-coded matrix `mult()` and `dot()`

Some basic matrix math. I've implemented a mult and a dot product as an exercise to refresh my memory on linear algebra.

In [11]:
from jkcsoft.math import jymath
import importlib

importlib.reload(jymath)

A = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
B = np.array([[5,6,7],[7,8,9]], dtype=np.float64)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")
print(f"A ndim: {A.ndim}")
print(f"A:\n{A}\n"
      f"B:\n{B}")

jims_product = jymath.matrix_multiply(A, B)

print(f"Jim's mat mult product:\n{jims_product}")

np_prod = np.matmul(A, B)

print(f"Numpy Product:\n{np_prod}")


A shape: (3, 2)
B shape: (2, 3)
A ndim: 2
A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
B:
[[5. 6. 7.]
 [7. 8. 9.]]
Jim's mat mult product:
[[19. 22. 25.]
 [43. 50. 57.]
 [67. 78. 89.]]
Numpy Product:
[[19. 22. 25.]
 [43. 50. 57.]
 [67. 78. 89.]]


## Matrices with NumPy

In [12]:
import numpy as np
# Example 1 - Matrix multiplication using @ operator and numpy.dot
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using @ operator
C = A @ B
# Using numpy.dot
D = np.dot(A, B)

print("Matrix Multiplication using @ operator:\n", C)
print("Matrix Multiplication using numpy.dot:\n", D)

# Example 2 - Matrix inverse and transpose
E = np.array([[1, 2], [3, 4]])
E_inverse = np.linalg.inv(E)
E_transpose = E.T

print("Matrix Inverse:\n", E_inverse)
print("Matrix Transpose:\n", E_transpose)

Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]
Matrix Multiplication using numpy.dot:
 [[19 22]
 [43 50]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Transpose:
 [[1 3]
 [2 4]]


Python `datetime`

In [13]:
from datetime import datetime, timedelta

print(f"Current date and time: {datetime.now()}")

# Create two datetime objects
start_time = datetime(2023, 10, 10, 15, 30, 25, 500000)  # Example datetime
end_time = datetime(2023, 10, 10, 15, 31, 26, 750000)  # Another datetime

# Calculate the difference (time delta) between the two
time_delta = end_time - start_time

# Get the total difference in milliseconds
milliseconds_difference = time_delta.total_seconds() * 1000

print(f"Time delta: {time_delta}")
print(f"Total difference in milliseconds: {milliseconds_difference:.3f} ms")

# Adding and subtracting time
new_time = start_time + timedelta(days=1, hours=-2)  # Add 1 day, subtract 2 hours
print(f"New time after adding 1 day and subtracting 2 hours: {new_time}")

# Add 3 seconds to the current time
now_plus_3_seconds = datetime.now() + timedelta(seconds=3)
print(f"Current date and time plus 3 seconds: {now_plus_3_seconds}")



Current date and time: 2025-03-12 13:24:47.859741
Time delta: 0:01:01.250000
Total difference in milliseconds: 61250.000 ms
New time after adding 1 day and subtracting 2 hours: 2023-10-11 13:30:25.500000
Current date and time plus 3 seconds: 2025-03-12 13:24:50.859885
