# Jim's take on Python math basics with builtins, `math` and `numpy`

## Python math built-ins: `min()`, `max()`, `pow()`, `...`

In [1]:

# Python has some built-in math functions
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

5
25


In [2]:
x = abs(-7.25)

print(x)

7.25


In [3]:
x = pow(4, 3)

print(x)

64


In [4]:
import math

x = math.sqrt(64)

print(x)

8.0


## Python `math` package

In [5]:
import math

x = math.ceil(1.4)
y = math.floor(1.4)

print(x)  # returns 2
print(y)  # returns 1

2
1


## `numpy` the magnificent

In [6]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])  # Create a rank 2 array
print(f"shape: {b.shape}\n"
      f"values:\n{b}")

shape: (2, 3)
values:
[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[[1, 2, 3], [4, 5, 6], [4, 5, 6]], [[7, 8, 9], [4, 5, 6], [10, 11, 12]]])

print(f"shape: {c.shape}\n"
      f"values:\n{c}")
print(f"ndim: {c.ndim}")
print(f"size: {c.size}")
print(f"dtype: {c.dtype}")
print(f"itemsize: {c.itemsize} bytes")
print(f"nbytes: {c.nbytes}")
print(f"data: {c.data}")
print(f"value at index [0,0,0]: {c[1,0,0]}")


shape: (2, 3, 3)
values:
[[[ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 4  5  6]
  [10 11 12]]]
ndim: 3
size: 18
dtype: int64
itemsize: 8 bytes
nbytes: 144
data: <memory at 0x10343b100>
value at index [0,0,0]: 7


## Re-entering the matrix: hand-coded matrix `mult()` and `dot()`

Some basic matrix math. I've implemented a mult and a dot product as an exercise to refresh my memory on linear algebra.

In [8]:
from jkcsoft.math import jymath
import importlib

importlib.reload(jymath)

A = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
B = np.array([[5,6,7],[7,8,9]], dtype=np.float64)

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")
print(f"A ndim: {A.ndim}")
print(f"A:\n{A}\n"
      f"B:\n{B}")

jims_product = jymath.matrix_multiply(A, B)

print(f"Jim's mat mult product:\n{jims_product}")

np_prod = np.matmul(A, B)

print(f"Numpy Product:\n{np_prod}")


A shape: (3, 2)
B shape: (2, 3)
A ndim: 2
A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
B:
[[5. 6. 7.]
 [7. 8. 9.]]
Jim's mat mult product:
[[19. 22. 25.]
 [43. 50. 57.]
 [67. 78. 89.]]
Numpy Product:
[[19. 22. 25.]
 [43. 50. 57.]
 [67. 78. 89.]]


## Matrices with NumPy

In [2]:
import numpy as np
# Example 1 - Matrix multiplication using @ operator and numpy.dot
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using @ operator
C = A @ B
# Using numpy.dot
D = np.dot(A, B)

print("Matrix Multiplication using @ operator:\n", C)
print("Matrix Multiplication using numpy.dot:\n", D)

# Example 2 - Matrix inverse and transpose
E = np.array([[1, 2], [3, 4]])
E_inverse = np.linalg.inv(E)
E_transpose = E.T

print("Matrix Inverse:\n", E_inverse)
print("Matrix Transpose:\n", E_transpose)

Matrix Multiplication using @ operator:
 [[19 22]
 [43 50]]
Matrix Multiplication using numpy.dot:
 [[19 22]
 [43 50]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Transpose:
 [[1 3]
 [2 4]]
